/*Insert States Data*/

INSERT INTO states(description, acronym) VALUES ('Alabama', 'AL');
INSERT INTO states(description, acronym) VALUES ('Alaska', 'AK');
INSERT INTO states(description, acronym) VALUES ('Arizona', 'AZ');
INSERT INTO states(description, acronym) VALUES ('Arkansas', 'AR');
INSERT INTO states(description, acronym) VALUES ('American Samoa', 'AS');
INSERT INTO states(description, acronym) VALUES ('California', 'CA');
INSERT INTO states(description, acronym) VALUES ('Colorado', 'CO');
INSERT INTO states(description, acronym) VALUES ('Connecticut', 'CT');
INSERT INTO states(description, acronym) VALUES ('Delaware', 'DE');
INSERT INTO states(description, acronym) VALUES ('District of Columbia', 'DC');
INSERT INTO states(description, acronym) VALUES ('Florida', 'FL');
INSERT INTO states(description, acronym) VALUES ('Georgia', 'GA');
INSERT INTO states(description, acronym) VALUES ('Guam', 'GU');
INSERT INTO states(description, acronym) VALUES ('Hawaii', 'HI');
INSERT INTO states(description, acronym) VALUES ('Idaho', 'ID');
INSERT INTO states(description, acronym) VALUES ('Illinois', 'IL');
INSERT INTO states(description, acronym) VALUES ('Indiana', 'IN');
INSERT INTO states(description, acronym) VALUES ('Iowa', 'IA');
INSERT INTO states(description, acronym) VALUES ('Kansas', 'KS');
INSERT INTO states(description, acronym) VALUES ('Kentucky', 'KY');
INSERT INTO states(description, acronym) VALUES ('Louisiana', 'LA');
INSERT INTO states(description, acronym) VALUES ('Maine', 'ME');
INSERT INTO states(description, acronym) VALUES ('Maryland', 'MD');
INSERT INTO states(description, acronym) VALUES ('Massachusetts', 'MA');
INSERT INTO states(description, acronym) VALUES ('Michigan', 'MI');
INSERT INTO states(description, acronym) VALUES ('Minnesota', 'MN');
INSERT INTO states(description, acronym) VALUES ('Mississippi', 'MS');
INSERT INTO states(description, acronym) VALUES ('Missouri', 'MO');
INSERT INTO states(description, acronym) VALUES ('Montana', 'MT');
INSERT INTO states(description, acronym) VALUES ('Nebraska', 'NE');
INSERT INTO states(description, acronym) VALUES ('Nevada', 'NV');
INSERT INTO states(description, acronym) VALUES ('New Hampshire', 'NH');
INSERT INTO states(description, acronym) VALUES ('New Jersey', 'NJ');
INSERT INTO states(description, acronym) VALUES ('New Mexico', 'NM');
INSERT INTO states(description, acronym) VALUES ('New York', 'NY');
INSERT INTO states(description, acronym) VALUES ('North Carolina', 'NC');
INSERT INTO states(description, acronym) VALUES ('North Dakota', 'ND');
INSERT INTO states(description, acronym) VALUES ('Northern Mariana Islands', 'MP');
INSERT INTO states(description, acronym) VALUES ('Ohio', 'OH');
INSERT INTO states(description, acronym) VALUES ('Oklahoma', 'OK');
INSERT INTO states(description, acronym) VALUES ('Oregon', 'OR');
INSERT INTO states(description, acronym) VALUES ('Pennsylvania', 'PA');
INSERT INTO states(description, acronym) VALUES ('Puerto Rico', 'PR');
INSERT INTO states(description, acronym) VALUES ('Rhode Island', 'RT');
INSERT INTO states(description, acronym) VALUES ('South Carolina', 'SC');
INSERT INTO states(description, acronym) VALUES ('South Dakota', 'SD');
INSERT INTO states(description, acronym) VALUES ('Tennessee', 'TN');
INSERT INTO states(description, acronym) VALUES ('Texas', 'TX');
INSERT INTO states(description, acronym) VALUES ('Trust Territories', 'TT');
INSERT INTO states(description, acronym) VALUES ('Utah', 'UT');
INSERT INTO states(description, acronym) VALUES ('Vermont', 'VT');
INSERT INTO states(description, acronym) VALUES ('Virginia', 'VA');
INSERT INTO states(description, acronym) VALUES ('Virgin Islands', 'VI');
INSERT INTO states(description, acronym) VALUES ('Washington', 'WA');
INSERT INTO states(description, acronym) VALUES ('West Virginia', 'WV');
INSERT INTO states(description, acronym) VALUES ('Wisconsin', 'WI');
INSERT INTO states(description, acronym) VALUES ('Wyoming', 'WY');